### ISSUE TITLE
exo很棒，部署遇到问题一起讨论起来哇

### ISSUE THREAD

**Issue by samcaicn** [exo-explore/exo#105]
exo很棒，在我调研的几个gpu产品如juice等几个软件相比较起来真的很好；
一起交流哇！
部署遇到问题一起讨论起来哇：
![image](https://github.com/user-attachments/assets/76803fed-7282-4c45-abf4-88d299c7e3c9)

添加验证消息exo，微信群名“exo应用讨论”

zed讨论组：gpustack

**Comment by AlexCheema** [comment]
> exo很棒，在我调研的几个gpu产品如juice等几个软件相比较起来真的很好； 一起交流哇！ 部署遇到问题一起讨论起来哇： ![image](https://private-user-images.githubusercontent.com/3318094/353804093-76803fed-7282-4c45-abf4-88d299c7e3c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjQyNzEsIm5iZiI6MTcyMjQyMzk3MSwicGF0aCI6Ii8zMzE4MDk0LzM1MzgwNDA5My03NjgwM2ZlZC03MjgyLTRjNDUtYWJmNC04OGQyOTljN2UzYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMTEwNjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE0ODI5OWE4NTc2MGVlMTRmNWJhZTY0NjM3NjYxOGY0MzI0Njg0Y2YzZjA2ZmM3NDU1Mzc5ODAyZmZhZDJmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hJDH4Yw5c-P1l5qH2hinyADi-L-aSrHHaPc0bB7TCk4)
> 
> 添加验证消息exo，微信群名“exo应用讨论”
> 
> zed讨论组：gpustack

Hey! DM'd on WeChat
