### ISSUE TITLE
Bug: server returns error on prompt (tinygrad)

### ISSUE THREAD

**Issue by hafezmg48** [exo-explore/exo#107]
When using the default prompt 
```
 http://localhost:9000/v1/chat/completions \
>   -H "Content-Type: application/json" \
>   -d '{
>     "model": "llama-3-8b",
>     "messages": [
>         {
>             "role": "user",
>             "content": "Why is the sky blue?"
>         }
>     ]
> }'
```
server returns error:
```
{"detail": "Error processing prompt (see logs with DEBUG>=2): TinygradDynamicShardInferenceEngine.infer_prompt() got multiple values for argument 'inference_state'"}
```
The server was working ok before adding the `image_str` to the `infer_prompt` which might be the reason why multiple values error happens.
P.S. I am running on Ubuntu with CUDA gpu. Python 3.12.3 with pytorch.

**Comment by AlexCheema** [comment]
Thanks for this! This was introduced by some recent changes to add support for vision models.
Fixed in https://github.com/exo-explore/exo/commit/76766253cde775f58f5637344dae2656f1c1447a
