### ISSUE TITLE
Error processing tensor for shard Shard(model_id='mlx-community/Meta-Llama-3.1-8B-Instruct-4bit', start_layer=16, end_layer=31, n_layers=32): Shapes (1,8,4,39,77) and (39,39) cannot be broadcast

### ISSUE THREAD

**Issue by wzLLM** [exo-explore/exo#130]
Hello, I encountered the following problems during use. The hardware is two MacBook Pro 128GB. Could you please tell me how to solve it? Thank you very much.

Waiting for response to finish. timeout=90s
[93fe91cb-af5c-415d-b219-bf8d24c33958] process_tensor: tensor.size=159744 tensor.shape=(1, 39, 4096)
Error processing tensor for shard Shard(model_id='mlx-community/Meta-Llama-3.1-8B-Instruct-4bit', start_layer=16, end_layer=31, n_layers=32): Shapes (1,8,4,39,77) and (39,39) cannot be broadcast.
Traceback (most recent call last):
  File "/Users/justing/Documents/LLMProject/exo/exo/orchestration/standard_node.py", line 217, in _process_tensor
    result, inference_state, is_finished = await self.inference_engine.infer_tensor(request_id, shard, tensor, inference_state=inference_state)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justing/Documents/LLMProject/exo/exo/inference/mlx/sharded_inference_engine.py", line 29, in infer_tensor
    output_data: np.ndarray = np.array(self.stateful_sharded_model.step(request_id, mx.array(input_data)))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justing/Documents/LLMProject/exo/exo/inference/mlx/sharded_model.py", line 48, in step
    output = self.model(y[None] if self.shard.is_first_layer() else y, cache=self.request_cache[request_id])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justing/Documents/LLMProject/exo/exo/inference/mlx/models/llama.py", line 89, in __call__
    out = self.model(inputs, cache)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/justing/Documents/LLMProject/exo/exo/inference/mlx/models/llama.py", line 66, in __call__
    h = layer(h, mask, cache=c)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mlx_lm/models/llama.py", line 247, in __call__
    r = self.self_attn(self.input_layernorm(x), mask, cache)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mlx_lm/models/llama.py", line 202, in __call__
    output = mx.fast.scaled_dot_product_attention(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Shapes (1,8,4,39,77) and (39,39) cannot be broadcast.
SendTensor tensor shard=Shard(model_id='mlx-community/Meta-Llama-3.1-8B-Instruct-4bit', start_layer=16, end_layer=31, n_layers=32) tensor=array([[[-0.2238 ,  0.0412 , -0.0925 , ...,  0.0702 , -0.279  ,
         -0.0901 ],
        [ 0.1188 ,  0.2231 ,  0.0677 , ...,  0.04755, -0.1328 ,
          0.02383],
        [-0.05267,  0.1637 ,  0.02417, ..., -0.05453, -0.4534 ,
          0.0687 ],
        ...,
        [ 0.1553 , -0.00583, -0.01239, ...,  0.00769, -0.2046 ,
          0.10516],
        [ 0.077  , -0.2004 , -0.02155, ..., -0.0756 , -0.1754 ,
          0.07446],
        [ 0.0653 , -0.1451 , -0.1365 , ..., -0.03104, -0.374  ,
          0.0512 ]]], dtype=float16) request_id='93fe91cb-af5c-415d-b219-bf8d24c33958' result: None

**Comment by AlexCheema** [comment]
Also getting this. Not sure when this was introduced. Doing a bisection now to figure out. Just tried 052ee1c which is quite far back but the issue isn't there. Will keep you updated and fix ASAP

**Comment by AlexCheema** [comment]
Does this only happen to you on the second request @wzLLM ?

To be the most likely culprit is some dependency... this goes way too far back for it to have been introduced by some change in exo. This was working fine yesterday for example.

**Comment by wzLLM** [comment]
Yes, it was the second time. In most cases, there is no problem with the first time, but this problem will appear in the second reasoning.

**Comment by wzLLM** [comment]
Yes, it was the second time. In most cases, there is no problem with the first time, but this problem will appear in the second reasoning.

**Comment by AlexCheema** [comment]
Hotfixed this. It is indeed only an issue with the second request, caused by changes in 5c67e24c35cdb1a0d1081623936df6ea03b198c8.
Will fix properly now.

**Comment by wzLLM** [comment]
got it, thank you very much
