### ISSUE TITLE
SyntaxError: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by PLK2** [exo-explore/exo#142]
Received the following error when running on PopOS Linux:

(.venv) pk@pop-os:~/exo$ python3 main.py
  File "/home/pk/exo/main.py", line 55
    print(f"Chat interface started:\n{'\n'.join([' - ' + terminal_link(web_chat_url) for web_chat_url in web_chat_urls])}")
                                                                                                                          ^
SyntaxError: f-string expression part cannot include a backslash

**Comment by AlexCheema** [comment]
Thanks, seems to happen on some versions of Python. Fixed.

**Comment by PLK2** [comment]
sweet--it works! Thanks!
