### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by tml2024** [exo-explore/exo#153]
The models you select in the chat window, can we add this one please?

[mlx-community](https://huggingface.co/mlx-community)

[Mistral-Large-Instruct-2407-bf16](https://huggingface.co/mlx-community/Mistral-Large-Instruct-2407-bf16)

**Comment by sambhavnoobcoder** [comment]
@AlexCheema i think this is implemented now , so kindly close this so that contributors don't end up implementing this all over again .

**Comment by tml2024** [comment]
Appreciated
