### ISSUE TITLE
BUG: Spaces between words are not streamed

### ISSUE THREAD

**Issue by vlbosch** [exo-explore/exo#164]
When using the TinyChat interface or connecting to exo via the HTTP API with for example TypingMind, the spaces between words are lost. I do see the spaces in the terminal environment, so I suppose the model is generating a correct response. It just seems to get lost when streaming to the client.

**Comment by AlexCheema** [comment]
> When using the TinyChat interface or connecting to exo via the HTTP API with for example TypingMind, the spaces between words are lost. I do see the spaces in the terminal environment, so I suppose the model is generating a correct response. It just seems to get lost when streaming to the client.

Hey, what devices are you running on?
What commit of exo are you using?

**Comment by vlbosch** [comment]
Hi! I am running exo on a M3 Max MacBook Pro with 128GB RAM with macOS 15.0 DP5 and the latest commit – [6db73fa]. Let me know if you need any other info

**Comment by AlexCheema** [comment]
Which model? I have the same setup and seems fine.

<img width="964" alt="Screenshot 2024-08-22 at 12 53 31" src="https://github.com/user-attachments/assets/fb40fb3a-5258-4419-ad34-113c184b59a9">

**Comment by vlbosch** [comment]
<img width="1917" alt="Scherm­afbeelding 2024-08-22 om 13 56 18" src="https://github.com/user-attachments/assets/3faa09e9-f6f8-4fc1-bcb4-bad28f1023c1">
I am running Mistral Large. Here's a screenshot of the terminal and the web-ui.

**Comment by AlexCheema** [comment]
Interesting..
Are you on Discord? I'd like to investigate some more and fix this for you.

**Comment by AlexCheema** [comment]
The next thing to check would be the network tab in your browser to see what is being sent over the wire.

**Comment by AlexCheema** [comment]
It's probably a tokenizer issue.

**Comment by vlbosch** [comment]
Yes I am :-)

**Comment by AlexCheema** [comment]
Let me know if this is fixed @vlbosch

**Comment by AlexCheema** [comment]
> I can confirm it works both in the Tiny webui as well as with the OpenAI compatibel HTTP API in Typing Mind. Thank you for this very fast fix! 😃🙏🏻

Awesome!

Please let me know if you run into any other issues, have suggestions for any improvements, or general comments. In particular, if you're annoyed by something or frustrated by something, please make an issue - it's really valuable to get this feedback so we can improve!
