### ISSUE TITLE
tinychat http 404 because no files

### ISSUE THREAD

**Issue by SJang1** [exo-explore/exo#172]
Happens after commit 3791e669a449f333797031095f5aa2d924f34f91
Almost all js files are getting HTTP 404 due to no files

No error log on the server, however not able to send any messages or upload anything due to no js working.

**Comment by samreid** [comment]
Same problem here. It looks like this for me and is nonfunctional:

<img width="1877" alt="image" src="https://github.com/user-attachments/assets/77f33ded-b033-470b-9aa7-0dedb99e0a91">

**Comment by AlexCheema** [comment]
Oh no, looks like I broke this just before my flight. I'm back with my laptop now so taking a look.

It's working on one of my MacBooks but not the other -- investigating.

**Comment by AlexCheema** [comment]
Should be fixed with https://github.com/exo-explore/exo/commit/8a4928f80c3e447b7bbb2e414f7904ef4f72164f
Can you let me know if it's fixed?

**Comment by SJang1** [comment]
I'm not on any of mac now, will check it later on. However if someone else could also check that would be great

**Comment by AlexCheema** [comment]
also just fixed some font 404's which were only cosmetic but should work now.

**Comment by samreid** [comment]
After the pushes above, it is working correctly on my system. Thanks!

Macbook Air M1
macOS Sonoma 14.6.1
Python 3.12.5

<img width="1781" alt="image" src="https://github.com/user-attachments/assets/98db4f4e-370e-419d-8826-3f60e4b68658">

**Comment by SJang1** [comment]
yes, seems like fixed now!
