### ISSUE TITLE
Node Connectivity Issues on Centos7

### ISSUE THREAD

**Issue by yuqiao9** [exo-explore/exo#181]
I've installed Exo on two Centos7
Tried starting the application with and also with debugging enabled:DEBUG_DISCOVERY=9 DEBUG=9 python3 main.py
I have started two EXO instances. In debug mode, they show that they have received broadcast packets from each other, but why does EXO still show only one node?
<img width="1066" alt="1" src="https://github.com/user-attachments/assets/522b0dc9-8cdd-44b7-8ebf-a89e8398f86b">

**Comment by AlexCheema** [comment]
Are they running on the same device? They seem to have identical node ids. You can explicitly set a node-id with `—node-id node1`
