### ISSUE TITLE
No module named 'exo.inference'

### ISSUE THREAD

**Issue by seasoncool** [exo-explore/exo#19]
I have installed exo lab with pip command , but still get new error like below:

Traceback (most recent call last):
  File "/home/drc-whlab/Downloads/exo-main/examples/llama3_distributed.py", line 5, in <module>
    from exo.inference.mlx.sharded_utils import get_model_path, load_tokenizer
ModuleNotFoundError: No module named 'exo'

**after: 'pip install exo'**

(exo) drc-whlab@drc-whlab:~/Downloads/exo-main/examples$ python llama3_distributed.py
Traceback (most recent call last):
  File "/home/drc-whlab/Downloads/exo-main/examples/llama3_distributed.py", line 5, in <module>
    from exo.inference.mlx.sharded_utils import get_model_path, load_tokenizer
ModuleNotFoundError: No module named 'exo.inference'

![image](https://github.com/user-attachments/assets/e6ce9843-97cf-4b9e-b5fd-b00193ecc7c6)

**Comment by AlexCheema** [comment]
You can’t install exo like this right now. Follow the README instructions and reopen the issue if you still run into problems. Thanks for creating an issue - if you run into more issues please don’t hesitate to create an issue.

**Comment by seasoncool** [comment]
thanks for you quick response.

you mean, i just type : python main.py  then used curl to send POST request ?

how about LLM ?  I don't know where is LLM config and load ?

**Comment by the-alex-b** [comment]
Awesome project! Thanks for building this :) 

I ran into the same issue as @seasoncool while following the instructions from the readme (installing from source using pip install -r requirements.txt). I guess it has to do with importing exo as a package while it's not installed in the python environment. 

For anyone running into this: Possible fix is to add a setup.py to the root of the project containing and installing the dependencies with `pip install .`

`from setuptools import setup, find_packages
import sys

# Base requirements for all platforms
install_requires = [
    "aiohttp==3.9.5",
    "grpcio==1.64.1",
    "grpcio-tools==1.64.1",
    "huggingface-hub==0.23.4",
    "Jinja2==3.1.4",
    "numpy==2.0.0",
    "protobuf==5.27.1",
    "psutil==6.0.0",
    "pynvml==11.5.3",
    "requests==2.32.3",
    "safetensors==0.4.3",
    "tiktoken==0.7.0",
    "tokenizers==0.19.1",
    "tqdm==4.66.4",
    "transformers==4.41.2",
    "uuid==1.30",
    "tinygrad @ git+https://github.com/tinygrad/tinygrad.git@a9f5a764dc640a5e5cbaaeeee21df7c8ca37da38",
]

# Add macOS-specific packages if on Darwin (macOS)
if sys.platform == "darwin":
    install_requires.extend(
        [
            "mlx==0.15.1",
            "mlx-lm==0.14.3",
        ]
    )


setup(
    name="exo",
    version="0.1.0",
    packages=find_packages(),
    install_requires=install_requires,
)
`
