### ISSUE TITLE
HF_ENDPOINT support

### ISSUE THREAD

**Issue by jshield** [exo-explore/exo#216]
seems like the HF_ENDPOINT env var is only partially supported, It retrieves metadata via it, but models are still resolved from the huggingface endpoint; looking at download.py, the base url appears to be hardcoded.

It might help to some extent with reducing upstream burden if a local caching service like https://github.com/vtuber-plan/olah can be used as a local mirror.

#217

**Comment by FromCSUZhou** [comment]
same question
