### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by vectrocomputers** [exo-explore/exo#219]
The README says to using the command:

`python3 main.py`

But the correct command is actually:

`CUDA=1 python3 main.py`

**Comment by nicholasyfu1** [comment]
I can fix this

**Comment by nicholasyfu1** [comment]
https://github.com/exo-explore/exo/pull/224

**Comment by AlexCheema** [comment]
I'm not sure about this. In tinygrad we use the default device which should be CUDA on an NVIDIA GPU instance.

<img width="668" alt="Screenshot 2024-09-20 at 17 17 23" src="https://github.com/user-attachments/assets/78ea8915-b6d9-4788-a24e-4bd497ccfe3a">

**Comment by AlexCheema** [comment]
Closing as I don't think this is necessary. Typically this means you didn't install CUDA.
