### ISSUE TITLE
How/when are model shards rebalanced when new nodes are added/removed?

### ISSUE THREAD

**Issue by fullofcaffeine** [exo-explore/exo#222]
Hi! 

First of all, thanks a bunch for this project! I'm pretty excited about the possibility of running more complex LLMs at home.

I have a couple of spare boxes at home, but some of them are not ready to join the cluster yet (need to update the OS, Python, etc). I'm wondering how are shards rebalanced as new nodes enter/leave the cluster. E.g: If a new node enters the cluster and I already had, let's say, llama 3.1 70b distributed across 2 nodes, will exo rebalance the shards across the new topology (of 3 nodes)? How and when? And what if the 3rd node leaves? 

Thanks in advance!

**Comment by AlexCheema** [comment]
Yes shards are automatically rebalanced as new nodes are added. This all happens behind the scenes.
Let me know if you run into any bugs there!
