### ISSUE TITLE
Issue with loading weights

### ISSUE THREAD

**Issue by JohnLee1360** [exo-explore/exo#231]
I am trying to use two MacBooks to run a Llama 8B model, but I can't load weights from the model to inference and stuck in 0 progress...
<img width="1536" alt="Screenshot 2024-09-24 at 12 03 28" src="https://github.com/user-attachments/assets/61314882-16a7-4ad7-923c-fa076201e8de">

Here's info of my equipments:
node1: MacBook Air 16GB with M3 chip
node2: MacBook Pro 16GB with M1 chip(Intel based)

Since my machine resource is limited, all of my machines run in tinygrad inference engine rather than in MLX. And I also wonder why my MacBook Pro shows 0TFLOPS?

I will be so appreciative if someone can offer me help~

**Comment by AlexCheema** [comment]
Can you try running with `SUPPORT_BF16=0`

**Comment by JohnLee1360** [comment]
Thanks for the reply!  I assume that `SUPPORT_BF16=0` means smaller quantized weights accuracy, right?
I gave it a shot, but it doesn't work. Maybe the problem stems from the different architecture of chips?

**Comment by AlexCheema** [comment]
> Thanks for the reply! I assume that `SUPPORT_BF16=0` means smaller quantized weights accuracy, right? I gave it a shot, but it doesn't work. Maybe the problem stems from the different architecture of chips?

No no this should definitely work.
Can you run with `DEBUG=6`. Are there any errors?

**Comment by JohnLee1360** [comment]
Thanks!!! DEBUG flag helps a lot!
But I wanna know different DEBUG flags stand for what? lol
