### ISSUE TITLE
Unable to format index.html

### ISSUE THREAD

**Issue by prajeshElEvEn** [exo-explore/exo#253]
In the file [`tinychat/examples/tinychat/index.html`](https://github.com/exo-explore/exo/blob/main/tinychat/examples/tinychat/index.html#L25) at line 25, and additional `</link>` closing tag is present.
This tag throws an error and prettier is unable to format this file.

![ss-20241001-002926Z-current](https://github.com/user-attachments/assets/6c7f4131-8b88-484b-b6bd-42873a3511b4)

Either you can assign me for this issue or you can just get rid of the extra `</link>` tag. I'd be willing to contribute to other issues though.

**Comment by AlexCheema** [comment]
good catch. assigned. go for it!

**Comment by prajeshElEvEn** [comment]
> good catch. assigned. go for it!

Created a [pull request](https://github.com/exo-explore/exo/pull/256).
You may verify and merge it.

**Comment by prajeshElEvEn** [comment]
Hey @AlexCheema 
I have created a new pull request #265, just as it was required.
