### ISSUE TITLE
System requirements 

### ISSUE THREAD

**Issue by shad-ct** [exo-explore/exo#254]
Please add the system requirements too. That'd be very helpful.

**Comment by larson-carter** [comment]
@shad-ct 

Did this PR solve what you are looking for: https://github.com/exo-explore/exo/pull/255

As seen in Alex's comment "The important thing is having enough VRAM across all your devices to fit the entire model in memory."

I guess in the future we can just pull stats every now and then, via a simply python script then update the readme if that is what you propose?

**Comment by AlexCheema** [comment]
Just updated the README since exo only requires that you have enough memory across all your devices and is designed to run on anything that has a Python runtime.

**Comment by AlexCheema** [comment]
Was there anything else you had in mind here @shad-ct
