### ISSUE TITLE
Can't pip install .

### ISSUE THREAD

**Issue by seasoncool** [exo-explore/exo#26]
according to guide :
cd exo
pip install .
# alternatively, with venv
source install.sh

get error:

![image](https://github.com/user-attachments/assets/4151d619-5978-4e49-94d7-d3d690953e12)

**Comment by AlexCheema** [comment]
hmm, `exo-2/exo-main/exo`... are you sure you're in the right directory? Make sure you're in the repo root.

I just tested this from fresh install (clean MacBook) so it definitely works: https://x.com/ac_crypto/status/1813817450204631112

**Comment by AlexCheema** [comment]
Let me know if that worked for you @seasoncool

**Comment by seasoncool** [comment]
You're right, I was using download instead of cloning, so my folder is called exo-main, not exo, thank you for your reply.
