### ISSUE TITLE
Feature request: specify GPU # if several installed 

### ISSUE THREAD

**Issue by FFAMax** [exo-explore/exo#296]
Found for now it will pick first shown by `nvidia-smi`

**Comment by FFAMax** [comment]
This also related partially to https://github.com/exo-explore/exo/issues/123

**Comment by AlexCheema** [comment]
I believe you can already do this with tinygrad by specifying `VISIBLE_DEVICES` see https://docs.tinygrad.org/env_vars/

**Comment by FFAMax** [comment]
> I believe you can already do this with tinygrad by specifying `VISIBLE_DEVICES` see https://docs.tinygrad.org/env_vars/

Got chance to verify it.
VISIBLE_DEVICES=0,1,2 and VISIBLE_DEVICES=1,2 will lead to the same result.
Also in manual mentioned it may work only for AMD|NV
Also opened a case to chase for it https://github.com/tinygrad/tinygrad/issues/7318
