### ISSUE TITLE
[BOUNTY - $100] Add support for LLaVA

### ISSUE THREAD

**Issue by AlexCheema** [exo-explore/exo#3]
**Motivation:** Vision models are useful.

**What:** exo supports different inference engines. Choose an inference engine (currently only MLX and tinygrad) for your implementation. You can probably find an existing LLaVA implementation somewhere (perhaps in https://github.com/ml-explore/mlx-examples for MLX). Modify that implementation to support sharded inference.

**Reward:** $100 Bounty paid out with USDC on Ethereum, email alex@exolabs.net.

**Comment by anirishrnbsinger** [comment]
taking a crack at this

**Comment by maciejjankowski** [comment]
> taking a crack at this

Pair programming?

**Comment by anirishrnbsinger** [comment]
What’s ur telegram? Discord?On 16 Jul 2024, at 17:38, Maciej Jankowski ***@***.***> wrote:﻿

taking a crack at this

Pair programming?

**Comment by AlexCheema** [comment]
go for it guys. just leave a comment here if you need any help or run into issues :) @maciejjankowski @anirishrnbsinger

**Comment by anirishrnbsinger** [comment]
Didn't make as much progress as would've hoped. Will be backed up with work for a couple days. Anyone else welcome to take a crack before then

**Comment by INF800** [comment]
Interesting stuff. Wanted to read more about this but docs seem to be WIP.

https://github.com/exo-explore/exo?tab=readme-ov-file#documentation

**Comment by INF800** [comment]
Ain't this as straightforward as using the code from [exo llama example](https://github.com/exo-explore/exo/blob/main/examples/llama3_distributed.py) and using it with [mlx llava example](https://github.com/ml-explore/mlx-examples/tree/main/llava)?

**Comment by INF800** [comment]
I can do pair programming, planning to do it on weekend 28th :) 

cc: @maciejjankowski

**Comment by INF800** [comment]
> Ain't this as straightforward as using the code from [exo llama example](https://github.com/exo-explore/exo/blob/main/examples/llama3_distributed.py) and using it with [mlx llava example](https://github.com/ml-explore/mlx-examples/tree/main/llava)?

cc: @AlexCheema 

And when can we expect the docs

**Comment by abhishek818** [comment]
attempting this..

**Comment by khushgx** [comment]
> *



> taking a crack at this

if yall still need help, would love to get involved. (Also do not care abt bounty and u can keep it)

**Comment by AlexCheema** [comment]
> > 
> 
> > taking a crack at this
> 
> if yall still need help, would love to get involved. (Also do not care abt bounty and u can keep it)

@khushgx looks like @varshith15 has started on it here: https://github.com/exo-explore/exo/pull/88

**Comment by varshith15** [comment]
im almost done sharding the model and removing duplicate code
if anyone wants to work on it, please pick up the client part of the code (UI changes) @khushgx

**Comment by AshirMehmood** [comment]
is there any thing I can contribute in ? @varshith15 @

**Comment by AlexCheema** [comment]
This is completed. Thanks @varshith15 don’t forget to shoot me an email alex@exolabs.net to claim your bounty payout.

**Comment by varshith15** [comment]
@AlexCheema emailed you a couple of days ago, varshith15@gmail.com 
Thanks!
