### ISSUE TITLE
error: no commands supplied

### ISSUE THREAD

**Issue by fdzl22** [exo-explore/exo#303]
Dear auth, my env is ubuntu24.04, rtx4070ti,vscode,python 3.12.04.

(.venv) (base) zhao@zhao-MS-7E13:~/桌面/exo$ python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

I do not kown save it, I attempt run python setup.py install,but is no happen.

**Comment by AlexCheema** [comment]
Please run `source install.sh`
You can't run `setup.py` directly that's not how it works.

**Comment by AlexCheema** [comment]
Please re-open if still an issue.

**Comment by fdzl22** [comment]
> 如果仍有问题，请重新打开。

Oh , I do it. Because the item word is not clearness. You need in run "source install.sh" end, un directly “exo”(Input at the terminal). Now,I have a new issue,the item is not it admit of only interpretation Llama3.1,And do not accept other models
