### ISSUE TITLE
如何添加其他节点

### ISSUE THREAD

**Issue by ZH4201** [exo-explore/exo#350]
我通过docker部署了项目但无法自动添加节点
![image](https://github.com/user-attachments/assets/5efffafe-2227-4f13-9e01-bb479058dcf4)
![image](https://github.com/user-attachments/assets/fe3b7fcf-03e9-44f9-a0f8-8e31a883b061)
![image](https://github.com/user-attachments/assets/bf79e54c-e5c0-476b-be61-a547b3af6b12)

**Comment by ji-cryptocafe** [comment]
exo 使用端口进行 UDP 通信和发现，你得通过 Docker 暴露这些端口
```docker run -d \
  -p 50051:50051/udp \
  -p 5678:5678/udp \
  -p 5679:5679/udp \
  your-image-name```
  
或用 compose.yaml
  
  ```services:
  your-service:
    image: your-image-name
    ports:
      - "50051:50051/udp"
      - "5678:5678/udp"
      - "5679:5679/udp"```
      
或用 dockerfile 
```
EXPOSE 50051/udp
EXPOSE 5678/udp
EXPOSE 5679/udp
```
