### ISSUE TITLE
How does the partition work?

### ISSUE THREAD

**Issue by mzbac** [exo-explore/exo#37]
When I was trying to shard the model for Deepseek v2 between 2 nodes, it seems the node receiving the request always tries to load the entire model without sharding.

**Comment by AlexCheema** [comment]
Right now, each node will download the entire model (issue for that: #16). But each node will only load the part of the model it needs (its partition) into memory and only execute that part.

**Comment by mzbac** [comment]
It seems the issue is due to the load_model for mlx model. It tries to load more weight than sharding layers, which can be challenging when trying to shard a big model on a small machine. I tried sharing 5 layers (<10GB weight) on my Mac M1 Max, but it keeps crashing due to OOM errors.
