### ISSUE TITLE
Cursor disappears post exo run

### ISSUE THREAD

**Issue by komikat** [exo-explore/exo#385]
Running `exo` after setup on mac causes the cursor to go away from the terminal after exo is done running.

A temporary fix can be just running `tput cnorm` ([from unix.stackexchange](https://unix.stackexchange.com/questions/609119/reset-cursor-state-without-reopening-terminal)) after exo is done running.

**Comment by AlexCheema** [comment]
What OS are you running on?

**Comment by komikat** [comment]
macOS Sonoma 14.5

**Comment by FFAMax** [comment]
command+r to reset terminal (iTerm)
