### ISSUE TITLE
Two node not connecting each other both on Ubuntu 

### ISSUE THREAD

**Issue by VGLALALA** [exo-explore/exo#425]
two different node is not seeing each other, they run as individuals.
One device is Ubuntu 22.04 other one is ubuntu 23 on wsl
Two devices is running on the same wifi

**Comment by prettydeep** [comment]
Looks like WSL on Windows [may not be supported](https://github.com/exo-explore/exo/issues/345#issuecomment-2412378311).

**Comment by develop-at-github** [comment]
@VGLALALA can you help the newcomers with the resolution to this issue? I am facing the same.
