### ISSUE TITLE
Error in peer discovery: '_UnixSelectorEventLoop' object has no attribute 'sock_recvfrom'

### ISSUE THREAD

**Issue by BenjaSOL** [exo-explore/exo#5]
Error occurs after installation when running:

`python3 main.py`

Environment:
Python 3.10.7
Mac M1

**Comment by AlexCheema** [comment]
Looks like something to do with the event loop implementation.

I'm working on a fix for you now.

**Comment by AlexCheema** [comment]
Can you try updating to the latest python version? There were a lot of asyncio related fixes recently. Let me know if that fixes it and I will also add to the README the minimum python version requirement.

**Comment by patchlog** [comment]
I also had the same errors with python 3.10 but no such errors with 3.11.7

**Comment by AlexCheema** [comment]
Added a notice in the README to require Python>=3.12.0: https://github.com/exo-explore/exo/commit/b6d91972fc2e78cf65d636fa2d20e8a6182b3f38

Please reopen the issue if this doesn't resolve the issue for you @BenjaSOL
