### ISSUE TITLE
How to set the max tokens for web ui?

### ISSUE THREAD

**Issue by southkorea2013** [exo-explore/exo#54]
Hello,

How to set the max tokens for the web ui? 

Thanks,
Nan

**Comment by AlexCheema** [comment]
Currently this isn’t configurable via the web ui. Just so I understand your use case, do you want to set the max tokens for all requests or per-request?

**Comment by southkorea2013** [comment]
Thanks Alex. I want to set the max tokens for all requests.

**Comment by itsknk** [comment]
Hey @AlexCheema, do you have any specific UI in mind?

I tried implementing it. It looks like this:

![Screenshot 2024-07-22 at 8 36 42 AM](https://github.com/user-attachments/assets/8796159c-9c8f-470f-a4ab-dbb4d8beef05)

**Comment by AlexCheema** [comment]
There is now a `--max-generate-tokens` argument you can pass when starting exo @southkorea2013
Example: `python3 main.py --max-generate-tokens 1000`
