### ISSUE TITLE
Response generation timed out

### ISSUE THREAD

**Issue by caohuilong** [exo-explore/exo#57]
create a cluster with 6 node，the topology as shown below
![image](https://github.com/user-attachments/assets/460c7ccd-a81a-4f42-9089-f4e3ea062268)

But when i send a request to the cluster，it always shows response generation timed out.
![image](https://github.com/user-attachments/assets/aa176569-1a36-4b34-bbf9-73cbbd2294df)

And sometimes the node that receives the request will output a lot of logs(i didn't find the errors message), and it will feel like the node's process is dead, the other nodes show only 5 nodes in the cluster.

**Comment by sgt-Script** [comment]
I am getting the same response.

**Comment by mintisan** [comment]
It seems that currently only the Mac platform is relatively stable, while other platforms have quite a few issues.
