### ISSUE TITLE
Update GitHub Profile URL from exolabs_ to https://x.com/exolabs

### ISSUE THREAD

**Issue by rifkiamil** [exo-explore/exo#581]
I noticed that the current GitHub profile https://github.com/exo-explore 

It points to https://x.com/exolabs_ which seems to be the old URL.

### Requested Action: 
Could you please update the profile link to the new URL https://x.com/exolabs?

### Additional Notes:
Please ensure that all documentation, headers, footers, and any other references are updated with the new URL.

**Comment by AlexCheema** [comment]
Good catch - fixed!
