### ISSUE TITLE
how to increase max tokens in tinychat? 

### ISSUE THREAD

**Issue by arthur-brainchain** [exo-explore/exo#59]
Hi, amazing progress over last few days, love the TUI.

I notice when I have tinychat open, I can't really modify max tokens. I tried grepping the repo for "514" since thats where it seems to stop at, but can't see it anywhere. I checked the backend API and I tried to pass in max_tokens in the frontend call. Any tips?

**Comment by AlexCheema** [comment]
As of https://github.com/exo-explore/exo/commit/b0e7dd9d2d1a8c957e8d48ab0c6950d13f41ddd5, there is now a `--max-generate-tokens` argument you can pass when starting exo @southkorea2013
Example: `python3 main.py --max-generate-tokens 1000`

**Comment by AlexCheema** [comment]
As of https://github.com/exo-explore/exo/commit/b0e7dd9d2d1a8c957e8d48ab0c6950d13f41ddd5, there is now a `--max-generate-tokens` argument you can pass when starting exo @southkorea2013
Example: `python3 main.py --max-generate-tokens 1000`
