### ISSUE TITLE
No feedback and very long delay

### ISSUE THREAD

**Issue by magnusviri** [exo-explore/exo#60]
I just tried this again with 23 nodes. It's been sitting here for a long time (I didn't time it but it's been many minutes and I'm giving up waiting):

<img width="526" alt="Screenshot 2024-07-22 at 17 47 51" src="https://github.com/user-attachments/assets/7c4649b1-c20e-4ab0-8888-e2e098b64b8d">

I assume it's downloading the model to nodes that don't have it but there's no feedback that's what it is doing.

<img width="878" alt="Screenshot 2024-07-22 at 17 47 16" src="https://github.com/user-attachments/assets/afc57a70-3c6d-48ef-aa1b-17942b49a273">

**Comment by AlexCheema** [comment]
Thanks so much for creating the issue.

We really need https://github.com/exo-explore/exo/issues/16
I gave it a crack just now but it requires a little more careful consideration.
I will give it another go tomorrow morning, along with some quality-of-life changes for large setups like this (e.g. download progress).

**Comment by magnusviri** [comment]
I tracked the delay to this https://github.com/exo-explore/exo/issues/70.

**Comment by moming2k** [comment]
Does that show it is downloading the model from the console UI interface? Otherwise, I need to find out if it is downloading the model from the network monitoring tools like Mac Activity monitor.

**Comment by magnusviri** [comment]
An older version of the cli showed the models downloading. The current version might, but I didn't notice it. I figured it out by watching the contents of the folder ~/.cache/huggingface/hub/.

**Comment by AlexCheema** [comment]
exo now shows download progress.
Also more QOL improvements in #124
