### ISSUE TITLE
cache per request

### ISSUE THREAD

**Issue by AlexCheema** [exo-explore/exo#67]
- Right now cache is shared between requests
- Although it will increase memory usage somewhat, we can afford to keep a cache per request
- Make `max_concurrent_requests` arg
- Automatically clean up caches that have not been updated for X minutes
- This should enable https://github.com/exo-explore/exo/issues/1 by having multiple caches in a batch for each request in the batch
- This would also then lead nicely into https://github.com/exo-explore/exo/issues/4 and perhaps also fix the root cause for https://github.com/exo-explore/exo/issues/61

**Comment by abdussamettrkr** [comment]
I am trying to create a unique cache for each request, but requests from the same chat in the web browser are creating different caches. Is that expected behavior?

**Comment by chunzha1** [comment]
It appears that currently the conversations in the web UI are not isolated?
