### ISSUE TITLE
Advantage over Groq

### ISSUE THREAD

**Issue by INF800** [exo-explore/exo#68]
Hi,

Is there any advantage over Groq atleast in therms of cost or speed?

Feels like using Groq would be cheaper and faster.

Thanks,
Rakesh

**Comment by magnusviri** [comment]
This is running locally on consumer hardware. Maybe it's not faster or even cheaper, but local is the selling point. It's private. It democratizes AI and gives anyone with normal consumer hardware the ability to run powerful AI.
