### ISSUE TITLE
Is windows supported ?

### ISSUE THREAD

**Issue by Kuinox** [exo-explore/exo#8]
I tried to install deps on a windows machine and got deps errors, I don't see anything about windows in the readme, so is windows supported ?

**Comment by AlexCheema** [comment]
Windows should work with the tinygrad inference engine, but I haven't tried it.
It seems a few people are getting dependency issues though so I will give Windows a try.

**Comment by Kuinox** [comment]
FYI on windows it fails to install MLX, which make sense since it's a Apple device thing.

**Comment by AlexCheema** [comment]
Right, that makes sense. Does it fail at `pip install -r requirements.txt`?

**Comment by Kuinox** [comment]
Yep

**Comment by AlexCheema** [comment]
Yeah, I had to hack around this before (removing from requirements.txt, moving around some code).
I will fix this properly as a priority first thing tomorrow.

**Comment by Kuinox** [comment]
I removed the 2 mlx deps from the file and it restore without problem.  
```
(myenv) PS C:\dev\exo> python3 main.py
Traceback (most recent call last):
  File "C:\dev\exo\main.py", line 6, in <module>
    from exo.orchestration.standard_node import StandardNode
  File "C:\dev\exo\exo\orchestration\__init__.py", line 2, in <module>
    from .standard_node import StandardNode
  File "C:\dev\exo\exo\orchestration\standard_node.py", line 4, in <module>
    from exo.inference.inference_engine import InferenceEngine, Shard
  File "C:\dev\exo\exo\inference\inference_engine.py", line 2, in <module>
    import mlx.nn as nn
ModuleNotFoundError: No module named 'mlx'
```
If i remove the mlx import, it start to fail at tinygrad imports (but I installed it ?) 

> I will fix this properly as a priority first thing tomorrow.  

Thanks a lot!

**Comment by wldasf** [comment]
I don't get why MLX is hardcoded into the project.

**Comment by AlexCheema** [comment]
> I don't get why MLX is hardcoded into the project.

exo supports different inference engines, MLX being one of them. That being said, MLX shouldn’t be a hard dependency and I will fix that.

**Comment by AlexCheema** [comment]
From tinygrad https://github.com/tinygrad/tinygrad/releases

You should still be able to use Windows with WSL. If you run into issues with that, please reopen the issue.

<img width="744" alt="Screenshot 2024-07-16 at 18 42 16" src="https://github.com/user-attachments/assets/3a9bf557-a993-48f9-97b7-5fc5f1d467ee">
