### ISSUE TITLE
AttributeError: 'GRPCPeerHandle' object has no attribute 'global_reset'

### ISSUE THREAD

**Issue by alphrc** [exo-explore/exo#85]
When I run the llama3_distributed.py with a local model, I got this error. I checked the class GRPCPeerHandle and its parent class, both do not have the 'global_reset' method

**Comment by AlexCheema** [comment]
I recently got rid of global_reset. Have you pulled the latest exo on each device?

**Comment by AlexCheema** [comment]
Closing as likely just running an old version. Please reopen if still an issue.
