### ISSUE TITLE
Running only in CPU

### ISSUE THREAD

**Issue by ManuXD32** [exo-explore/exo#89]
I know llama.cpp is not implemented already. Does it mean it isn't possible to run models on CPU yet?

**Comment by AlexCheema** [comment]
You can with the tinygrad inference engine. Just run exo with CLANG=1 to force it to use CPU

**Comment by mct2611** [comment]
@AlexCheema  Hi AlexCheema, can u please explain that how to run with CLANG=1?

**Comment by ManuXD32** [comment]
> @AlexCheema Hi AlexCheema, can u please explain that how to run with CLANG=1?

Just write "CLANG=1 python3 main.py"
It works, but I haven't gotten my cluster to be really usable. I'm really looking forward to see how this project turns out, it's very promising.
