### ISSUE TITLE
Keep waiting for response after initiating a chat request

### ISSUE THREAD

**Issue by duguyixiaono1** [exo-explore/exo#92]
Hi , I am a newbie. I started running on a device, and after initiating a chat request, it keeps waiting for a response. The debug information is as follows. What could be happening?

`Sending prompt from ChatGPT api request_id='643c0946-6367-470f-bf47-47db1928be2c'
shard=Shard(model_id='mlx-community/Meta-Llama-3.1-8B-Instruct-4bit', start_layer=0, end_layer=0, n_layers=32)
prompt='<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nhi<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n'
[643c0946-6367-470f-bf47-47db1928be2c] process prompt: base_shard=Shard(model_id='mlx-community/Meta-Llama-3.1-8B-Instruct-4bit', start_layer=0,
end_layer=0, n_layers=32) shard=Shard(model_id='mlx-community/Meta-Llama-3.1-8B-Instruct-4bit', start_layer=0, end_layer=31, n_layers=32)
prompt='<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nhi<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n'
Starting with the following peers: []
Connecting to new peers...
Collecting topology max_depth=4 visited=set()
Fetching 6 files:   0%|                                                                                                    | 0/6 [00:00<?, ?it/s]
Topology collection task executed.
Current topology: Topology(Nodes: {0a80abbf-a7e4-4273-8b9c-477adfec9de7: Model: MacBook Air. Chip: Apple M3. Memory: 24576MB. Flops: fp32: 3.55
TFLOPS, fp16: 7.10 TFLOPS, int8: 14.20 TFLOPS}, Edges: {})
Starting with the following peers: []
Connecting to new peers...
Collecting topology max_depth=4 visited=set()
Topology collection task executed.
Current topology: Topology(Nodes: {0a80abbf-a7e4-4273-8b9c-477adfec9de7: Model: MacBook Air. Chip: Apple M3. Memory: 24576MB. Flops: fp32: 3.55
TFLOPS, fp16: 7.10 TFLOPS, int8: 14.20 TFLOPS}, Edges: {})`

**Comment by AlexCheema** [comment]
It’s downloading the model. It takes some time to do for the first time on each device,
